### ISSUE TITLE
Custom cursor implementation

### ISSUE THREAD

**Issue by dashed** [omniscientjs/immstruct#41] opened 2015-03-02 21:18 UTC
Figured I start this discussion.

From my rambling: https://gitter.im/omniscientjs/omniscient?at=54f4cc9a9622a2fc57f66790

I suggested that omniscientjs would eventually provide its own implementation of cursors that extend from immutable lib. 

This would essentially be a fork/rewrite of https://github.com/facebook/immutable-js/tree/master/contrib/cursor

Some obvious features to add:
- Official API for `keyPath`.
- ~~`Cursor.isCursor()` See: https://github.com/facebook/immutable-js/issues/300 Maintainer seems to disagree to add this static method in favour of type transparency.~~

Ideas:
- Handle observations in a more fundamental way than at userland (e.g. immstruct) (possible?)

/cc @Gozala

**Comment by mikaelbr** [comment] 2015-03-02 21:41
This is definitely a viable approach. As far as I know, Lee Byron isn't interested in maintaining the Cursor implementation and if it makes sense for us, doing a custom implementation might be favorable.

It depends somewhat on what direction is the best, though. It might be that just extending immstruct (allowing us to take more opinionated and special implementations for Omniscient) is still a better approach. But I think the idea is definitely something we should discuss.

**Comment by Gozala** [comment] 2015-03-02 21:52
The reason I proposed a fork was to have a way of resolving an issue of animation frame same as om.

Current problem (that was already outlined is gitter) with cursors can be illustrated as:

```js
const not = x => !x;
// ...
ToggleButton({ onClick: event => cursor.update(‘isChecked’, not)})
```
If `onClick` is invoked even number of times with in the same animation frame result will be unexpected, the problem is render won't run there for event handler will refer to cursor that has out of date knowledge of the state.

I do believe this is a reason why om has two ways to defer cursor https://github.com/omcljs/om/wiki/Cursors#consistency-and-observability `(deref cursor)` to get current state one `(om/value cursor)` to get rendered state.

I think adding such a capability to cursors would likely be necessary to handle async rendering.

**Comment by Gozala** [comment] 2015-03-02 21:57
I realised I clicked a wrong link on email and end up posting my response to Facebook/immutbale-js#300 instead of here :( But I tend to fully agree with maintainer in regards to `isCursor` check, as he basically suggest to do exactly what I was aiming for in #76 The only reason why `isCursor` is necessary is to to out of equality check provided by a cursor implementation which I still think better to leave up to implementer.

**Comment by Dashed** [comment] 2015-03-03 02:52
Alright, I think we can get around `isCursor` with `valueOf`. I demonstrated this by revamping https://github.com/omniscientjs/omniscient/pull/78, see: https://github.com/omniscientjs/omniscient/pull/85

**Comment by mikaelbr** [comment] 2015-03-03 07:32
So as far as I can tell, what we'd really need is the distinction between `.value()` and `.deref()`. In this way we have two choices:

1. Patching cursors created by immstruct.
2. Creating new cursor library as an alternative to immutable.js cursors.

I'm not sure patching would be the best apporach, as you'd have to patch every cursor created as sub-cursors - allthough it would be possible and probably wouldn't require too much code.

The draw backs of creating a new cursor library, however, is that we'd have to maintain more code and take more generic needs into consideration.

**Comment by Dashed** [comment] 2015-03-03 09:12
At the moment, it seems viable to extend the cursor library.

----

Posting here for posterity.

Working concept of wrapping cursors: https://gist.github.com/Dashed/27c0d2a20d8e53e1447e

**Comment by Gozala** [comment] 2015-03-03 21:30
I think it would be best to decide exactly what we want out of cursors library that is currently not provided by immutable.js. Then try to discuss those changes with a maintainer to see if there is a chance we could collaborate to get them inn. Finally if we can't convince them to have those changes and they can't convince use we don't need them we could fork a repo and do those changes.

In my personal experience cursors provided by immutable.js seem to work great as is BTW, only thing that they don't quite support well IMO is case for async rendering, but maybe they do have some ideas on that or maybe they could be convinced to match API of Om (which I imagine can be done as Immutable.js itself is basically clojure data structures implemented in JS).

**Comment by nbostrom** [comment] 2015-05-15 21:45
Arch's cursors might be worth looking at. They built their own implementation instead of using contrib/cursor because they wanted observable cursors: https://github.com/redbadger/arch/blob/master/src/cursor.ls

It's written in livescript, but it shouldn't be too hard to read even if you're not familiar with it.

Might be a good source of inspiration.

**Comment by Dashed** [comment] 2015-05-15 22:23
@nbostrom Cool. Awesome to see what other folks have done. Have you personally used this implementation?

**Comment by nbostrom** [comment] 2015-05-16 15:45
@Dashed, nope

**Comment by jameshopkins** [comment] 2015-09-14 23:05
I appreciate this is a pretty inactive thread, but I've only just come across it.

I've recently submitted a patch for Immutable JS' cursor implementation (https://github.com/facebook/immutable-js/pull/622) that I believe fixes the issue (https://github.com/facebook/immutable-js/issues/618) that @Gozala was referring to. I had no idea until reading this thread that the current implementation isn't really maintained - which is a shame, because I really like the fact many of Immutable's List and Map methods are available directly on the cursor.

I'd be interested to hear where the current train of though it headed with regards to a cursor implementation for Immstruct.

**Comment by Dashed** [comment] 2015-09-14 23:28
@jameshopkins Cool PR! 

> Instead of each cursor holding it's own reference to the root data, every cursor now shares a common reference to the root data. (source: https://github.com/facebook/immutable-js/pull/622)

I pretty came to the same conclusions for my own [experimental] cursor implementation (merging cursor and reference cursor); and reaped all the benefits of single-source-of-truth:

- https://github.com/Dashed/providence (base cursor)
- https://github.com/Dashed/probe (observation extension)

Unfortunately, this [the PR] drastically changes the semantics for cursor as implemented in immutable-js library; and I'm unsure the maintainer/author is open is such a change.

-----

Since there are more "cursor" implementations being popped up; a fork/rewrite of a cursor library, as I originally suggested in the first post, may be one direction immstruct may take. Bonus points if such an implementation can be independent of a immutable library.

**Comment by mikaelbr** [comment] 2015-09-15 05:48
Cool, this would definitely solve some of the patching immstruct is forced to do. But as @Dashed points out, this is a pretty huge change in the semantics, and if I'd have to guess, Lee Byron won't be too thrilled about making this change. This PR also changes that cursors are immutable them self.

I can see immstruct maybe supporting different cursor implementations (if all planets align and there is a common base interface), but it might be difficult to support different immutable implementations. Not impossible, but might be unpractical.

**Comment by jameshopkins** [comment] 2015-09-16 15:24
Not sure if it's of any use to you guys, but given the apparent lack of enthusiasm for Immutable.js to merge my PR, I've decided to fork the cursor into it's own project. https://github.com/omniscientjs/immstruct/issues/41. My intention is to actively maintain it and respond to PRs promptly if and when they happen.

**Comment by mikaelbr** [comment] 2017-05-01 08:32
`immutable-cursor` is now in use.

**Closed** 2017-05-01 08:32 UTC
